site_name: TripSage AI API Documentation
site_description: Comprehensive API documentation for TripSage AI travel planning system
site_author: TripSage Team
site_url: https://tripsage-ai.readthedocs.io/

repo_url: https://github.com/tripsage-ai/tripsage-ai
repo_name: tripsage-ai/tripsage-ai
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 TripSage Team

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: table
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_bases: true
            show_category_heading: true
            show_docstring_attributes: true
            show_docstring_classes: true
            show_docstring_functions: true
            show_docstring_modules: true
            show_if_no_docstring: true
            show_inheritance_diagram: true
            show_labels: true
            show_object_full_path: false
            show_root_full_path: true
            show_root_heading: true
            show_root_toc_entry: true
            show_signature: true
            show_signature_annotations: false
            show_source: false
            show_submodules: false
            signature_crossrefs: true
            summary: true
          paths: [tripsage, tripsage_core]
          import:
            - https://docs.python.org/3/objects.inv
          selection:
            filters:
              - "!^_"  # exclude private members
              - "!^__"  # exclude dunder members
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: tripsage-ai
      repo: tripsage-ai
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
      - Overview: api/README.md
      - Authentication: api/auth.md
      - Quick Start: api/usage-examples.md
  - API Reference:
      - REST Endpoints: api/rest-endpoints.md
      - WebSocket API:
          - Overview: api/websocket-realtime-api.md
          - Connection Guide: api/websocket-connection-guide.md
          - Events Guide: api/websocket-events-guide.md
          - Integration Guide: api/websocket-integration-guide.md
      - Dashboard API: api/dashboard-api.md
      - Error Codes: api/error-codes.md
  - Interactive API:
      - OpenAPI Spec: openapi.md
  - Code Reference:
      - tripsage package: reference/tripsage/
      - tripsage_core package: reference/tripsage_core/