/**
 * Agent Status tracking types - now using Zod schemas for runtime validation
 *
 * @deprecated Direct type imports - use Zod schemas from /lib/schemas/agent-status.ts instead
 * This file now re-exports types from the Zod schemas for backward compatibility
 */

// Re-export types from Zod schemas for backward compatibility
export type {
  AgentStatusType,
  TaskStatus,
  SessionStatus,
  AgentTask,
  Agent,
  AgentActivity,
  ResourceUsage,
  AgentSession,
  WorkflowConnection,
  AgentWorkflow,
  AgentConfig,
  AgentMetrics,
  AgentState,
  CreateAgentTaskRequest,
  UpdateAgentTaskRequest,
  CreateAgentRequest,
  UpdateAgentRequest,
  CreateWorkflowRequest,
  UpdateWorkflowRequest,
  AgentStatusUpdate,
  TaskStatusUpdate,
  ResourceUsageUpdate,
  AgentWebSocketMessage,
  AgentFormData,
  TaskFormData,
  WorkflowFormData,
} from "../lib/schemas/agent-status";

// Re-export schemas for validation
export {
  agentStatusTypeSchema,
  taskStatusSchema,
  sessionStatusSchema,
  agentTaskSchema,
  agentSchema,
  agentActivitySchema,
  resourceUsageSchema,
  agentSessionSchema,
  workflowConnectionSchema,
  agentWorkflowSchema,
  agentConfigSchema,
  agentMetricsSchema,
  agentStateSchema,
  createAgentTaskRequestSchema,
  updateAgentTaskRequestSchema,
  createAgentRequestSchema,
  updateAgentRequestSchema,
  createWorkflowRequestSchema,
  updateWorkflowRequestSchema,
  agentStatusUpdateSchema,
  taskStatusUpdateSchema,
  resourceUsageUpdateSchema,
  agentWebSocketMessageSchema,
  agentFormSchema,
  taskFormSchema,
  workflowFormSchema,
  validateAgentData,
  validateAgentTask,
  validateWorkflow,
  safeValidateAgent,
  safeValidateTask,
  safeValidateWorkflow,
  calculateSuccessRate,
  isAgentActive,
  getAgentLoad,
  canAcceptNewTask,
} from "../lib/schemas/agent-status";
