/**
 * Agent Status tracking types - now using Zod schemas for runtime validation
 *
 * @deprecated Direct type imports - use Zod schemas from /lib/schemas/agent-status.ts instead
 * This file now re-exports types from the Zod schemas for backward compatibility
 */

// Re-export types from Zod schemas for backward compatibility
export type {
  Agent,
  AgentActivity,
  AgentConfig,
  AgentFormData,
  AgentMetrics,
  AgentSession,
  AgentState,
  AgentStatusType,
  AgentStatusUpdate,
  AgentTask,
  AgentWebSocketMessage,
  AgentWorkflow,
  CreateAgentRequest,
  CreateAgentTaskRequest,
  CreateWorkflowRequest,
  ResourceUsage,
  ResourceUsageUpdate,
  SessionStatus,
  TaskFormData,
  TaskStatus,
  TaskStatusUpdate,
  UpdateAgentRequest,
  UpdateAgentTaskRequest,
  UpdateWorkflowRequest,
  WorkflowConnection,
  WorkflowFormData,
} from "../lib/schemas/agent-status";

// Re-export schemas for validation
export {
  agentActivitySchema,
  agentConfigSchema,
  agentFormSchema,
  agentMetricsSchema,
  agentSchema,
  agentSessionSchema,
  agentStateSchema,
  agentStatusTypeSchema,
  agentStatusUpdateSchema,
  agentTaskSchema,
  agentWebSocketMessageSchema,
  agentWorkflowSchema,
  calculateSuccessRate,
  canAcceptNewTask,
  createAgentRequestSchema,
  createAgentTaskRequestSchema,
  createWorkflowRequestSchema,
  getAgentLoad,
  isAgentActive,
  resourceUsageSchema,
  resourceUsageUpdateSchema,
  safeValidateAgent,
  safeValidateTask,
  safeValidateWorkflow,
  sessionStatusSchema,
  taskFormSchema,
  taskStatusSchema,
  taskStatusUpdateSchema,
  updateAgentRequestSchema,
  updateAgentTaskRequestSchema,
  updateWorkflowRequestSchema,
  validateAgentData,
  validateAgentTask,
  validateWorkflow,
  workflowConnectionSchema,
  workflowFormSchema,
} from "../lib/schemas/agent-status";
