global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tripsage-monitor'

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  # Scrape metrics exported by OTEL collector
  - job_name: 'tripsage-metrics'
    static_configs:
      - targets: ['otel-collector:8889']

  # Scrape DragonflyDB metrics directly
  - job_name: 'dragonfly-direct'
    static_configs:
      - targets: ['dragonfly:6379']
    metrics_path: /metrics
    params:
      format: ['prometheus']

  # Scrape TripSage API metrics (when available)
  # CONFIGURATION NOTES for different development setups:
  # - Docker Desktop (Windows/Mac): Use 'host.docker.internal:8000'
  # - Linux Docker: Use 'localhost:8000' or '172.17.0.1:8000' (Docker bridge IP)
  # - API running in Docker: Replace with service name, e.g., 'tripsage-api:8000'
  # - Custom port: Update port number if API runs on different port
  - job_name: 'tripsage-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: /metrics
    # Scrape interval for API metrics
    scrape_interval: 30s
    # Timeout for scraping API metrics
    scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - '/etc/prometheus/alerts/*.yml'