global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tripsage-monitor'

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  # Scrape metrics exported by OTEL collector
  - job_name: 'tripsage-metrics'
    static_configs:
      - targets: ['otel-collector:8889']

  # Scrape DragonflyDB metrics directly
  - job_name: 'dragonfly-direct'
    static_configs:
      - targets: ['dragonfly:6379']
    metrics_path: /metrics
    params:
      format: ['prometheus']

  # Scrape TripSage API metrics (when available)
  - job_name: 'tripsage-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - '/etc/prometheus/alerts/*.yml'