name: Cache Vite/Vitest/TS/Next.js
description: Reusable cache step for Vite, Vitest, TypeScript, and Next.js build info
runs:
  using: composite
  steps:
    - name: Cache Vite/Vitest/TS/Next.js caches
      uses: actions/cache@v4
      with:
        # Generic key prefix 'caches' to cover Vite, Vitest, TS, and Next.js build caches.
        # Note: Changing from 'vite-vitest-' key causes one-time cache miss on merge; this is acceptable
        # for configuration improvements. Descriptor was broadened to reflect full cache scope.
        key: ${{ runner.os }}-caches-${{ hashFiles('pnpm-lock.yaml','vitest.config.ts','tsconfig.json','package.json','next.config.ts') }}
        restore-keys: |
          ${{ runner.os }}-caches-
        path: |
          node_modules/.vite
          node_modules/.vitest
          .vitest-cache
          .next/cache
