"""Pydantic models for direct API integrations.

This package contains data models for the direct API service implementations,
replacing the previous MCP server abstraction layer.
"""

from tripsage_core.models.api.accommodation_models import (
    AccommodationDetailsRequest,
    AccommodationDetailsResponse,
    SavedAccommodationRequest,
    SavedAccommodationResponse,
)
from tripsage_core.models.api.calendar_models import (
    CalendarEvent,
    CalendarList,
    CreateEventRequest,
    EventDateTime,
    EventReminder,
    UpdateEventRequest,
)
from tripsage_core.models.api.itinerary_models import (
    ItineraryConflictCheckResponse,
    ItineraryCreateRequest,
    ItineraryItemCreateRequest,
    ItineraryItemResponse,
    ItineraryItemType,
    ItineraryItemUpdateRequest,
    ItineraryOptimizeRequest,
    ItineraryOptimizeResponse,
    ItineraryResponse,
    ItinerarySearchRequest,
    ItinerarySearchResponse,
    ItineraryShareSettings,
    ItineraryStatus,
    ItineraryUpdateRequest,
    Location,
    OptimizationSetting,
    TimeSlot,
)
from tripsage_core.models.api.trip_models import (
    CreateTripRequest,
    TripCollaboratorResponse,
    TripCollaboratorsListResponse,
    TripCollaboratorUpdateRequest,
    TripListItem,
    TripListResponse,
    TripPreferencesRequest,
    TripResponse,
    TripShareRequest,
    TripSuggestionResponse,
    TripSummaryResponse,
    UpdateTripRequest,
)
from tripsage_core.models.api.weather_models import (
    CurrentWeather,
    DailyForecast,
    HourlyForecast,
    WeatherAlert,
    WeatherCondition,
    WeatherForecast,
)


__all__ = [
    "AccommodationDetailsRequest",
    "AccommodationDetailsResponse",
    "CalendarEvent",
    "CalendarList",
    "CreateEventRequest",
    "CreateTripRequest",
    "CurrentWeather",
    "DailyForecast",
    "EventDateTime",
    "EventReminder",
    "HourlyForecast",
    "ItineraryConflictCheckResponse",
    "ItineraryCreateRequest",
    "ItineraryItemCreateRequest",
    "ItineraryItemResponse",
    "ItineraryItemType",
    "ItineraryItemUpdateRequest",
    "ItineraryOptimizeRequest",
    "ItineraryOptimizeResponse",
    "ItineraryResponse",
    "ItinerarySearchRequest",
    "ItinerarySearchResponse",
    "ItineraryShareSettings",
    "ItineraryStatus",
    "ItineraryUpdateRequest",
    "Location",
    "OptimizationSetting",
    "SavedAccommodationRequest",
    "SavedAccommodationResponse",
    "TimeSlot",
    "TripCollaboratorResponse",
    "TripCollaboratorUpdateRequest",
    "TripCollaboratorsListResponse",
    "TripListItem",
    "TripListResponse",
    "TripPreferencesRequest",
    "TripResponse",
    "TripShareRequest",
    "TripSuggestionResponse",
    "TripSummaryResponse",
    "UpdateEventRequest",
    "UpdateTripRequest",
    "WeatherAlert",
    "WeatherCondition",
    "WeatherForecast",
]
